In [23]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import(
    mean_absolute_error,
    mean_squared_error,
    r2_score
) 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("../data/preprocessed_housing.csv")
df.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,False,False,False,False,True,False,False,False,True,False
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,False,False,False,False,True,False,False,False,True,False
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,False,False,False,False,True,False,False,False,True,False
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,False,False,False,False,True,False,False,False,False,False
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,False,False,False,False,True,False,False,False,True,False

In [3]:
x=df.drop(columns=["Id","SalePrice"])
y=df["SalePrice"]

In [4]:
X_train,X_test,Y_train,Y_test=train_test_split(
    x,y,test_size=0.2,random_state=42
)

In [12]:
scalar=StandardScaler()
X_trained_scaled=scalar.fit_transform(X_train)
X_test_scaled=scalar.transform(X_test)

In [29]:
results = []

LINEAR REGRESSION MODEL

In [13]:
lr_model=LinearRegression()
lr_model.fit(X_trained_scaled,Y_train)
y_pred_lr=lr_model.predict(X_test_scaled)

In [27]:
mae_lr=mean_absolute_error(Y_test,y_pred_lr)
mse_lr=mean_squared_error(Y_test,y_pred_lr)
rmse_lr=mse**0.5
r2_lr=r2_score(Y_test,y_pred_lr)
print(f"MAE : {mae_lr:.2f}")
print(f"MSE : {mse_lr:.2f}")
print(f"RMSE : {rmse_lr:.2f}")
print(f"R^2 : {r2_lr:.4f}")

MAE : 23927.04
MSE : 6909851338.71
RMSE : 45162.76
R^2 : 0.0991

In [30]:
results.append({
    "Model": "Linear Regression",
    "MAE": mae_lr,
    "RMSE": rmse_lr,
    "R2": r2_lr
})

DECISION TREE MODEL

In [25]:
dt_model = DecisionTreeRegressor(random_state=42)
dt_model.fit(X_train,Y_train)
y_pred_dt=dt_model.predict(X_test)

In [31]:
mae_dt = mean_absolute_error(Y_test, y_pred_dt)
mse_dt = mean_squared_error(Y_test, y_pred_dt)
rmse_dt = mse ** 0.5
r2_dt = r2_score(Y_test, y_pred_dt)
print(f"MAE : {mae_dt:.2f}")
print(f"MSE : {mse_dt:.2f}")
print(f"RMSE : {rmse_dt:.2f}")
print(f"R²   : {r2_dt:.4f}")

MAE : 28227.33
MSE : 2039674898.98
RMSE : 45162.76
R²   : 0.7341

In [32]:
results.append({
    "Model": "Decision Tree",
    "MAE": mae_dt,
    "RMSE": rmse_dt,
    "R2": r2_dt
})

RANDOM FOREST

In [33]:
rf_model = RandomForestRegressor(random_state=42)
rf_model.fit(X_train,Y_train)
y_pred_rf=rf_model.predict(X_test)

In [34]:
mae_rf = mean_absolute_error(Y_test, y_pred_rf)
mse_rf = mean_squared_error(Y_test, y_pred_rf)
rmse_rf = mse_rf ** 0.5
r2_rf = r2_score(Y_test, y_pred_rf)

print(f"MAE : {mae_rf:.2f}")
print(f"MSE : {mse_rf:.2f}")
print(f"RMSE: {rmse_rf:.2f}")
print(f"R²  : {r2_rf:.4f}")

MAE : 17678.80
MSE : 851419245.02
RMSE: 29179.09
R²  : 0.8890

In [35]:
results.append({
    "Model": "Random Forest",
    "MAE": mae_rf,
    "RMSE": rmse_rf,
    "R2": r2_rf
})

XGBOOST

In [36]:
xgb_model = XGBRegressor(
    random_state=42,
    objective="reg:squarederror"
)
xgb_model.fit(X_train, Y_train)
y_pred_xgb = xgb_model.predict(X_test)

In [37]:
mae_xgb = mean_absolute_error(Y_test, y_pred_xgb)
mse_xgb = mean_squared_error(Y_test, y_pred_xgb)
rmse_xgb = mse_xgb ** 0.5
r2_xgb = r2_score(Y_test, y_pred_xgb)

print(f"MAE : {mae_xgb:.2f}")
print(f"MSE : {mse_xgb:.2f}")
print(f"RMSE: {rmse_xgb:.2f}")
print(f"R²  : {r2_xgb:.4f}")

MAE : 17920.20
MSE : 818506368.00
RMSE: 28609.55
R²  : 0.8933

In [38]:
results.append({
    "Model": "XGBoost",
    "MAE": mae_xgb,
    "RMSE": rmse_xgb,
    "R2": r2_xgb
})

In [39]:
results_df = pd.DataFrame(results)
results_df.sort_values(by="R2", ascending=False).reset_index(drop=True)

               Model           MAE          RMSE        R2
0            XGBoost  17920.199219  28609.550294  0.893289
1      Random Forest  17678.798562  29179.089174  0.888998
2      Decision Tree  28227.325342  45162.760090  0.734082
3  Linear Regression  23927.037738  45162.760090  0.099145